In [1]:
#matrix and their basic operations

In [2]:
x=[1,2,3,4,5]

In [3]:
import numpy as np
x=np.array([1,2,3,4,5])

In [4]:
print(x)

[1 2 3 4 5]


In [5]:
m=np.array([[1,5,2],
          [4,7,4],
          [2,0,9]])
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [7]:
print('Matrix Transpose: \n',m.transpose(), '\n')

Matrix Transpose: 
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 



In [8]:
print('Matrix Determinant: ',np.linalg.det(m),'\n') #linalg-performing linear algebra operation

Matrix Determinant:  -105.00000000000006 



In [10]:
m_inv=np.linalg.inv(m)
print('Matrix inverse: \n',m_inv,'\n')

Matrix inverse: 
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



In [11]:
iden_m=np.dot(m,m_inv)
iden_m=np.round(np.abs(iden_m),0)
print('Product of matrix and its inverse: \n', iden_m)

Product of matrix and its inverse: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
eigen_vals, eigen_vecs= np.linalg.eig(m)
print('Eigen values: \n',eigen_vals,'\n')
print('Eigen vectors: \n',eigen_vecs)

Eigen values: 
 [-1.32455532 11.32455532  7.        ] 

Eigen vectors: 
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


In [13]:
U,S,VT= np.linalg.svd(m)    #singal value decomposition
print('Getting SVD outputs:- \n')
print('U:\n',U,'\n')
print('S:\n',S,'\n')
print('VT:\n',VT,'\n')

Getting SVD outputs:- 

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



In [15]:
zeros_array=np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
ones_array=np.ones((4,3),dtype=np.int32)   #specifying dtype
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
